### ISSUE TITLE
[Bug] Screenshot is not generated when configuring screenshot_on_error:true

### ISSUE THREAD

**Issue by dhoanglong91** [WasiqB/coteafs-appium#112]
Configuration of appium-config.xml:
![Screen Shot 2020-10-26 at 2 25 33 PM](https://user-images.githubusercontent.com/40136031/97144516-2dc02600-1797-11eb-8a2b-4f629d059b58.png)

I modified testDoubleTap() to make it fail:
![Screen Shot 2020-10-26 at 2 24 55 PM](https://user-images.githubusercontent.com/40136031/97144537-33b60700-1797-11eb-860c-fb73e20db371.png)

Actual result:
The test failed but not screenshot is generated

Expected result:
Screenshot should be generated

**Comment by WasiqB** [comment]
@dhoanglong91 , Thanks for raising the issue. I have started restructuring and re-writing the project and in the process will keep this issue in consideration. Once the re-write is done, I'll update here separately so you can check if the issue is fixed.
