### ISSUE TITLE
Invalid flag --release error

### ISSUE THREAD

**Issue by seesiva** [WasiqB/coteafs-appium#124]
when providing mvn clean install -DskipTests=true the following error occurs. 
 invalid flag: --release

Using the following maven environment
![image](https://user-images.githubusercontent.com/3206488/107590480-39443980-6c2e-11eb-9729-3ee1193b9160.png)

Any suggestions?

**Comment by seesiva** [comment]
Subsequently I tried adding the plugin to the pom.xml, still the error persists.
<build>
    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <version>3.8.0</version>
            <configuration>
                <source>1.8</source>
                <target>1.8</target>
            </configuration>
        </plugin>
    </plugins>
</build>

**Comment by WasiqB** [comment]
@seesiva , you must use JDK 11 instead of JDK 1.8. Update `JAVA_HOME` with JDK 11 path and it should work for you.

**Comment by seesiva** [comment]
@WasiqB Issue got resolved with JDK 11. Thanks. It helps.
