### ISSUE TITLE
[Query] can this framework handles react js ?

### ISSUE THREAD

**Issue by RollerIn** [WasiqB/coteafs-appium#175]
As I have observed selenium with java, lot of challenges to handle react application because waiting for each element till rendering
while loading react application , will it able to keep WebDriver session without ending? I mean keeping driver to wait until react application render or each react element render?

Thanks for your lot of support and patience.

**Comment by WasiqB** [comment]
@RollerIn , the framework supports testing React native apps. You can check our tests which runs on a react native app.
