### ISSUE TITLE
Error while Starting Appium Server

### ISSUE THREAD

**Issue by mfaisalkhatri** [WasiqB/coteafs-appium#18]
[server-1.log](https://github.com/WasiqB/coteafs-appium/files/1424124/server-1.log)
## Description
System displays the following error when user tries to run the Test using external: false in the config file:
"FAILED CONFIGURATION: @BeforeSuite setupSuite
com.github.wasiqb.coteafs.appium.error.AppiumServerNotStartingError: Error occured while starting Appium server"

Config file details are as follows:
servers: 
  android:  
    ip: 127.0.0.1
    port: 4723
    external: false
    
    arguments:
      log_level: DEBUG
      log_time_stamp: true
      local_time_zone: true
      suppress_adb_kill_server: true

## Environment

* Appium server version: 1.7.1
* Desktop OS version: Windows 8.1
* coteafs-appium version: 2.0.0.
* Mobile platform version: Android / 4.4.2
* Real device / simulator: Real Device

## Details

Check log files for more details.

[ErrorLog.txt](https://github.com/WasiqB/coteafs-appium/files/1424123/ErrorLog.txt)

**Comment by mfaisalkhatri** [comment]
[server-1.log](https://github.com/WasiqB/coteafs-appium/files/1424125/server-1.log)
Server1.log file is attached.

**Comment by WasiqB** [comment]
I tried replicating the issue, but it's working on my end. Can you try again and comment the gist link for the complete stack trace when you face the same issue again?

**Comment by mfaisalkhatri** [comment]
This is not an issue, actually, windows 8 took some time to start the appium server, so I increased the session_timeout: 120000, previously it was session_timeout: 6000 in the config file.
It is working fine now.
Closing the Issue.
