### ISSUE TITLE
System should check battery health before running tests on device.

### ISSUE THREAD

**Issue by mfaisalkhatri** [WasiqB/coteafs-appium#60]
## Description

System should check the battery health of the device before running tests.
If battery is less than 20%, than tests should not run and message should be logged as "Low battery, please connect to charger and re-run test".

### Edit
This feature will only be supported when Automation name is UIAutomator2. Refer [here](https://github.com/appium/java-client/issues/1039) for confirmation from Appium maintainers.

**Comment by WasiqB** [comment]
Issue has been raised in Appium java-client as getting Battery info generates Error.
Issue can be found [here](https://github.com/appium/java-client/issues/1039).
