### ISSUE TITLE
Port handling is required for cloud platform, like saucelab.

### ISSUE THREAD

**Issue by mfaisalkhatri** [WasiqB/coteafs-appium#62]
## Description

Handling of port in the url is required for testing in cloud platform like saucelabs.
E.g.
public static final String USERNAME = "YOUR_USERNAME";
public static final String ACCESS_KEY = "YOUR_ACCESS_KEY";
public static final String URL = "https://" + USERNAME + ":" + ACCESS_KEY + "@ondemand.saucelabs.com:443/wd/hub";
Here, port: "443" is required to be input in case of saucelab url.

**Comment by WasiqB** [comment]
Now you can add port for saucelabs in config under `port` key.
